### ISSUE TITLE
Stops sending logs if a connection issue is encountered

### ISSUE THREAD

**Issue by masimakopoulos** [logentries/le_node#101]
Hi, 

I am using the latest version of the module together with the latest version of bunyan. Everything works until a connection issue appears (e.g. remote service is down, lost network connectivity etc) which results in no more logs being sent to log entries until I restart the process.
I simulated this issue by doing the following. I start my process and start logging. I can see logs in log entries live trace normally. I then disconnect the machine from the internet for a couple of minutes but continue logging. I then restore the internet connection, but no logs are sent to log entries any more until I restart the scenario.

```
var loggerDefinition = Logger.bunyanStream({token: loggerConfig.token, minLevel: 2});

var logger = bunyan.createLogger({
    name: 'myLogger',
    src: process.env.NODE_ENV === 'development', // slow, do not use in production
    serializers: {
        err: bunyan.stdSerializers.err,
        req: reqSerializer,
        res: bunyan.stdSerializers.res
    },
    streams: [loggerDefinition, {level: 'debug', stream: process.stdout}]
});
```

I tried hooking to loggerDefinition.stream events (error, connected, etc), but non of the seems to get fired. Any idea what is happening?

**Comment by yieme** [comment]
Getting the same issue with 1.3.0 when just using the le_node library. To repeat:

- Do some logging (which verifies all is well)
- Disable the network connection
- Do some logging (don't expect these to go thru but it would be nice if they queued)
- Enable the network connection
- Do some logging (nothing goes thru to logentries.com)

**Comment by masimakopoulos** [comment]
This is still an issue for me too. Unfortunately this issue has not received any love since I first posted it.

**Comment by yieme** [comment]
Yes, as as we can't seem to detect that the logentries component has failed then we can't force a restart. Until the problem is corrected we can't get alerts from the logentries service as no data is flowing. If you've only one instance, you may notice you aren't getting telemetry; however, if you have multiple instances going, it becomes a silent fail. Not good as logs are an important part of monitoring and auditing.

In the meantime, we're left with a couple of hack options:

1) use another service to detect network connection. [Firebase example:](https://stackoverflow.com/questions/11351689/detect-if-firebase-connection-is-lost-regained)

```js
var firebaseRef = new Firebase('http://INSTANCE.firebaseio.com');
firebaseRef.child('.info/connected').on('value', function(connectedSnap) {
  if (connectedSnap.val() === true) {
    /* we're connected! */
  } else {
    /* we're disconnected! */
  }
});
```

The problem with this is if the connection fail is a logentries service connection fail instead of our application connection failing, we end up in the same boat.

2) Force a restart at some time interval. If you're running on Heroku the apps are auto restarted daily so this would accomplish the same thing if you can live with up to 24 hours of lost logs.

Any other mitigation thoughts you have @masimakopoulos?

**Comment by masimakopoulos** [comment]
Not really. We are facing the same issues, having random nodes failing to log in production and not realising we have lost their logging. Our workaround involves frequent restarts of the services and error monitoring through New Relic (we get buffer full errors in le_node when a lot of logs have tried to be written whilst offline). 
This is a major hustle for us and we are looking into alternatives for our logging needs.

**Comment by StephenHynes7** [comment]
Is anything logged internally by the library when this occurs?

**Comment by yieme** [comment]
@masimakopoulos, sounds like you have the second option in place. Does uncaughtException inform you of the buffer full errors?

```
process.on('uncaughtException', function (err) {
  // if err is le_node buffer full, restart
})
```

**Comment by masimakopoulos** [comment]
Ha... good point. It might. But this is my uncaughtExceptionHandler
```
process.on('uncaughtException', function handleUncaughtException(err) {
    logger.fatal({err: err}, 'application crashed.');
    process.exit(1);
});
```
which probably will not complete as it tries to log to le_node first

**Comment by yieme** [comment]
If you can't determine the specific error, wrapping the logger.fatal() in a try..except might work.

```
process.on('uncaughtException', function handleUncaughtException(err) {
    try {
      logger.fatal({err: err}, 'application crashed.');
    } catch(e) {}
    process.exit(1);
});
```

**Comment by bathos** [comment]
I haven't looked at the connection logic in the better part of a year now. My understanding of the `net.Socket` connection is probably not deep enough for me to address this with much confidence. Is handling timeout not enough?

**Comment by yieme** [comment]
Having loss in our access log audit trail isn't really something we are in a position to live with for long.

**Comment by StephenHynes7** [comment]
Okay I have the reproducible scenario, fun fact the lib does recover from connection issues but only if you reconnect to the network within less than a minute. I have a weird feeling it's to do with the back off var here that it grows to such a huge size that it becomes impossible to reconnect.

**Comment by StephenHynes7** [comment]
@yieme @masimakopoulos by any chance can you try setting https://github.com/logentries/le_node/blob/master/src/node_modules/defaults.js#L6 to a really large amount and trying again? I think we burn through this value hence why we never reconnect. Also I am finding it incredibly difficult to debug the library so this will be a slowish process =/

**Comment by masimakopoulos** [comment]
I can try changing the value, but not sure when and if I will know the difference, as the loss of connection occurs randomly. I believe this needs a more concrete way to test it in order to make sure it is fixed appropriately.

**Comment by StephenHynes7** [comment]
@masimakopoulos i agree, ideally the logic here should be completely redone in the same vain as https://github.com/logentries/le_java/blob/master/src/main/java/com/logentries/net/AsyncLogger.java#L529 since the current logic is brittle in that it will eventually give up and never try again.

**Comment by StephenHynes7** [comment]
FYI please look at https://github.com/logentries/le_node/pull/116#event-735340198 with regards this issue.

**Comment by StephenHynes7** [comment]
The fix for this is on NPM.
