### ISSUE TITLE
Node-inspector unable handle console = true

### ISSUE THREAD

**Issue by fchengpc** [logentries/le_node#104]
i run my node-inspector then with console=true, it will crash everytime. Node-inspector print an empty object but somehow my terminal is fine. Is this a bug??

<img width="721" alt="screen shot 2016-04-07 at 4 25 55 pm" src="https://cloud.githubusercontent.com/assets/6640631/14365770/6e867538-fcdd-11e5-9c53-4ddf16e9bda9.png">

**Comment by bathos** [comment]
I think so, in that the following behavior should either be documented or changed: the console option only supports logging objects / JSON.

I'm surprised this hasn't surfaced before actually. Can you confirm that what you were logging was just a string message or similar? If so, does logging an object work?

**Comment by fchengpc** [comment]
Yeah i'm only logging some request info out to LE in JSON string format. I try an object this morning and saw the same issue. 
If this is bug, is there a work around for now?

**Comment by bathos** [comment]
If you're seeing the issue with objects, I don't think it's related to what I first suspected was the issue. Can you show how to reproduce it?

**Comment by fchengpc** [comment]
Here is my version >> Node Inspector v0.12.5 & le_node 1.2.0. 
node-inspector run and with sample code blow:
```sh   
var test = new Logger({ token: token, console: true });
    test.info({
        "x": "1",
        "xx": "2",
        "xxx": "3",
        "xxxx": "4"
    });
```

**Comment by bathos** [comment]
Sorry, @fchengpc, I should have specified to test it with `node`. At a glance it looks like node-inspector is a pretty hefty tool that may change how any number of the normal systems it needs to intercept work, and one of the areas they're patching is logging, so I couldn't predict how it might interact with le_node.

**Comment by fchengpc** [comment]
i see, just node is fine. all the terminal output is fine. just not with node-inspector. Guess you can close.
