### ISSUE TITLE
"Le_node" does not work under higher load.

### ISSUE THREAD

**Issue by arcseldon** [logentries/le_node#109]
Hi. I have built several log extensions for `Auth0` that allow our customers to export their log data to their log aggregator of choice. To date, I have written ones for `splunk`, `papertrail`, `sumologic`, `loggly`, `logstash` and `mixpanel` with no issues.  Recently had a request from a customer for a similar extension for `logentries` so went ahead and wrote one leveraging this NPM module for the log / transport.

Please see screenshot:

![extensions](https://cloud.githubusercontent.com/assets/2599332/15314262/d04da54c-1c4b-11e6-9756-1debe589f63a.jpg)

This worked when I tested locally, however in production, the customer that requested this feature is experiencing problems.  Have tried increasing the `bufferSize` but it does not work. 

Here is the error trace `LogentriesError: Buffer is full, unable to log:`:

```
body: "{ "code": 500, "error": "Script generated an unhandled asynchronous exception.", "details": "LogentriesError: Buffer is full, unable to log: \"info {\"date\":\"2016-04-11T ...\".", "name": 

"LogentriesError", "message": "Buffer is full, unable to log: \"info {\"date\":\"2016-04-11T ...\".", "stack": "LogentriesError: Buffer is full, unable to log: \"info {\"date\":\"2016-04-11T ...\".\n at Logger.log (/data/_verquire/le_node/1.0.8/node_modules/le_node/lib/node_modules/logger.js:346:24)\n at LogentriesTransport.log 

(/data/_verquire/le_node/1.0.8/node_modules/le_node/lib/node_modules/logger.js:690:21)\n at emit (/data/_verquire/le_node/1.0.8/node_modules/le_node/node_modules/winston/lib/winston/logger.js:186:17)\n at /data/_verquire/pusher/1.2.1/node_modules/pusher/node_modules/webpack/node_modules/watchpack/node_modules/async/lib/async.js:122:13\n at _each 

(/data/_verquire/pusher/1.2.1/node_modules/pusher/node_modules/webpack/node_modules/watchpack/node_modules/async/lib/async.js:46:13)\n at Object.async.each (/data/_verquire/pusher/1.2.1/node_modules/pusher/node_modules/webpack/node_modules/watchpack/node_modules/async/lib/async.js:121:9)\n at Logger.log 

(/data/_verquire/le_node/1.0.8/node_modules/le_node/node_modules/winston/lib/winston/logger.js:214:9)\n at Object.winston.(anonymous function) [as log] (/data/_verquire/le_node/1.0.8/node_modules/le_node/node_modules/winston/lib/winston.js:87:34)\n at Object.target.(anonymous function) [as info] 

(/data/_verquire/le_node/1.0.8/node_modules/le_node/node_modules/winston/lib/winston/common.js:52:18)\n at /data/authenticom%2F31e12b262ea97e3d50b2c5d0ef29f85a:138:18" }"
```

With the other log providers, each provider has made a `http collector endpoint` available. Here we are relying on TCP underlying transport. 

The code that does the log setup is [here](https://github.com/auth0/auth0-logs-to-logentries/blob/master/index.js#L21)  (all our extensions are open source):

and the log call itself [here](https://github.com/auth0/auth0-logs-to-logentries/blob/master/index.js#L89) - if you can offer any insights as to why this would fail with `bufferFull` I'd be grateful - we run our exports as a CRON with a maximum of 100 log entries per run, and a minimum of 1 minute between runs so really we are dealing with very low volumes?

Thanks in advance. We'd really like to get this working - if all else fails then I may have to either drop support for `logentries` or find / write my own NPM module for handling the transport layer (sigh..)  Thanks again.

**Comment by arcseldon** [comment]
One of the fundamental difficulties here, is that I could see no easy way to get a `callback` after logs have been made, and there was no appropriate `event` to listen for either so I have wrapped with `winston` which provides this in an attempt to get acknowledgements.

**Comment by StephenHynes7** [comment]
@arcseldon I have seen that we burn through the buffer in very simple test applications
```js
var Logger = require('le_node');
var logger = new Logger({ token: 'xxxx' });
for(var i = 0; i<1000;i++){
	logger.warning('Int: ' + i)
}
```

Run this with a token and you will see it fails fairly quickly with the buffer full error. Possibly I think there is a bottleneck somewhere in the system, my gut feeling is that the size of the buffer is way way way way too small and that leads to the problem. I have a PR to increase the default size as shown here https://github.com/logentries/le_node/pull/108 the caveat being is that if there is a bottleneck in terms of processing and forwarding log events then the app will end up using a lot of memory. 

I would be interested in seeing though if your buffer is that sort of size do you run into the same problem and whether you get any performance hits.

**Comment by bathos** [comment]
The example code here: `for(var i = 0; i<1000;i++){ ...` is a *synchronous* loop. Excepting specialized and unusual cases (which is why the buffer size is configurable), putting 1000 items into a stream *in a single tick* is pretty clear sign of a problem in the code. If these events were queued asynchronously (even if very quickly, let's say five per tick), then we should hope the buffer does not fill, and if it still does, I think that suggests a different or additional problem to address.

As for callbacks, this is unfortunately not possible without awkward wheel reinvention & expensive overhead. Log entries are sent to LE over an open TLS connection as string data with a delimiter character between entries. There is no individual transaction we can monitor, it's just a stream of characters being piped along. We could introduce a mechanism to send "one at a time", but that seems to go against the principle which I assume made LE choose this channel in the first place (speed and low-overhead?). Plus, in the end, if we were successful, we would have invented "the HTTP request" :)

**Comment by arcseldon** [comment]
@bathos - thanks for your reply - still unable to proceed here.

My case is that I need to send a maximum of 100 log entries per cron run (scheduled job) which triggers at most once per minute. In other words, simply send 100 logs per minute, and I need a means of acknowledgement that the 100 log entries were sent successfully once sent.  How do I achieve this please?

Regarding your final comment above:

> Plus, in the end, if we were successful, we would have invented "the HTTP request"

That's actually what I want...., and (at least one) way all the other log aggregators provide write access. Does `LogEntries` provide an HTTP collector endpoint?  In other words, is it possible to send logs to `logentries` over http(s) instead, and avoid using `le_node` (as a last resort)?

**Comment by StephenHynes7** [comment]
@arcseldon we do have a HTTPS endpoint. See here http://docs.logentries.com/docs/http-post

**Comment by arcseldon** [comment]
@StephenHynes7 - Thank you.  This looks like the right approach for our particular scenario with regards to sending data over given the conversations above. Will use this for integration and report back here with results.

**Comment by arcseldon** [comment]
@StephenHynes7 - incidentally, why does the documentation for input types only refer to:

```
Input types are:
Token TCP - logs are identified by a token Learn more...
Plain TCP/UDP - logs are sent via syslog Learn more...
Agent - log files are followed by the agent Learn more...
HTTP PUT - log entries are sent using HTTP PUT Learn more...
```

**Comment by StephenHynes7** [comment]
@arcseldon We are migrating our old doc site over to this new one (The older one became increasingly more difficult to maintain and keep up to date due to how it was hosted) as such a lot of doc changes that I wanted to make before are actually being enforced, for example HTTP PUT which we eventually want to deprecate will no longer be documented BUT our HTTP POST method will be. 

Once we successfully migrate we will then start changing the various links from within our App to reflect the changes.

**Comment by arcseldon** [comment]
@StephenHynes7 - thanks for providing some context. Have a couple of questions please regarding the HTTP Post endpoint. 

1. Is the token provided the same as for TCP ?  The link is broken where it states `HTTP POST relies on a User supplying a Token in the same way that Token TCP forwarding method does.`

2. Does the POST work with Content-Type `application/json`  ?  Or does this HAVE to be `application/x-www-form-urlencoded` etc?

3. Does the format HAVE to be `data=data`   where in our case the data `value` will actually be JSON content.

Thanks for your ongoing input - as you say the docs are slightly light on specifics atm.

**Comment by StephenHynes7** [comment]
1. Yes it is. I will update the doc to make this more clear!

2. Yes it does! 

``` curl
curl -H "Content-Type: application/json" -X POST -d '{"username":"foo","email":"bar@foo.com"}' http://webhook.logentries.com/noformat/logs/5b26ee19-7439-4740-9d79-3fd6b4b96618
```
3. No that's just how I formatted the code to use in my code.

**Comment by arcseldon** [comment]
Thanks for confirmation. All your answers tally with what I have already done. As I say, I receive a 204 but nothing is appearing when I live tail the logs. Will keep digging.

**Comment by StephenHynes7** [comment]
If you get a 204 then everything is good! Usually I test this by enabling live tail first and letting it run for a minute or two and then sending the data via HTTP POST, it should then be picked up and display. Also double check you are tailing the correct log. If you  still aren't having any luck let me know!

**Comment by arcseldon** [comment]
@StephenHynes7 - Thanks again. Had no luck until i deleted my old log completely, and recreated a new one. Now, again I receive a 204 but am seeing the log entries. The only code I altered was the value for the new token. No idea why the old log had simply stopped working but thank you again for the assistance all the same.  This works now identically to how the TCP version did, I am about to test what happens when I batch up into blocks of 100. Keep you posted on results.

**Comment by StephenHynes7** [comment]
@arcseldon could be that you were using the wrong token? 

The only caveat to be aware of atm is that the body size is limited to 8k character size, if you go over it then the message will be dropped, I know that we are trying to change this to be a lot bigger (probably 64k) but it is something to be aware of for the moment.

**Comment by arcseldon** [comment]
@StephenHynes7 - in your docs for HTTP post you state - `The maximum number of characters that can be included in the body is 8192, if you exceed this limit then you message will be dropped.`  Can you remove this restriction or increase it if need be?

For `sumologic` I wrote an NPM module that allows me to introduce a `bulk` option - see [logs-to-sumologic](https://github.com/tawawa/logs-to-sumologic) 

Similar support exists in npm modules for other log aggregators such as `loggly` too.

Is there a real need for the restriction?

**Comment by arcseldon** [comment]
@StephenHynes7 - have tested locally using `async.js` and batching requests in blocks of 5 for cycles of 100 logs at a time. It works great using the HTTP Post endpoint. It would be really nice to be able to just send out the 100 log entries in a single bulk call but hopefully what we now have is sufficient to go into PRD.

**Comment by StephenHynes7** [comment]
@arcseldon no there is not, I think it was the long is a piece of string sort of thing where 8k was chosen. For the record we have a bug against this behaviour and we wish to up it to 64k.

**Comment by arcseldon** [comment]
@StephenHynes7 - If you do up the limit to 64K please let me know and I shall modify a small NPM module I wrote today that would support `bulk` mode. This is [logs-to-logentries](https://www.npmjs.com/package/logs-to-logentries)  - there might be better options out there for most usecases - including `le-node`, and `node-logentries` etc. However, for the particular case I had, this one seems to actually fit nicely. 

Will now update our Logentries Extension on Auth0 to use the `logs-to-logentries` module and await feedback from Customer on whether it fixes the issue raised. Shall post here once more with that outcome, and hopefully close the issue too. Once again, thank you very much for the input!

**Comment by sirkirby** [comment]
Thanks @arcseldon and @StephenHynes7 for working through this! I'll be testing the update to the Auth0 extension as soon as it's available.

**Comment by arcseldon** [comment]
@StephenHynes7 - Great, this is working well for us in Production (so far...)  Appreciate your input.

@sirkirby - Thank you for re-installing the auth0 extension and re-testing. Great to see this solved.
