### ISSUE TITLE
handleExceptions

### ISSUE THREAD

**Issue by Apathetic012** [logentries/le_node#15]
```javascript
var logentries = require('node-logentries')
  var log = logentries.logger({
    token:'123'
  })

  app.configure('production', function() {
    log.winston(winston, {handleExceptions: true})
  })
```

When there's an uncaught exception it should be able to catch the error and log it. It works on other transports like `winston.transports.File`.

**Comment by bathos** [comment]
The handleExceptions property is Winston’s -- it’s inherited from Winston’s "Transport" constructor. It doesn’t matter what the transport in question is, you’re just indicating that you want Winston to send expections there. However it may not have worked correctly in the old le_node because if Winston sends the actual Error object (not sure if they do), le_node wouldn’t have been able to serialize it correctly. The new client can.

**Comment by voitau** [comment]
It does not seem to work with 1.0.6 though. Please let me know if I'm doing something wrong here:
```
var winston = require('winston');
var Logger = require('le_node');

var logger = new (winston.Logger)({
  transports: [
    new winston.transports.Logentries({
      handleExceptions: true,
      json: true,
      token: 'le_token_goes_here'
    })
  ]
});

module.exports = logger;
```

**Comment by bathos** [comment]
Thanks! When I went to check this out, it solved #61 for me :)

I stared at that forever and couldn't make sense of it. I was looking for something complex but it was a stupid typo. The fix will hopefully solve both problems ... expect it in a minute or two.

**Comment by voitau** [comment]
Okay, there is a log entry now. But of this format though:
```
25 Jun 2015 21:09:23.967 error uncaughtException: connect ECONNREFUSED "[object Object]"
```
Other messages as well:
```
25 Jun 2015 21:10:37.172 info HTTP GET / "[object Object]"
```
Checked with the previous version (1.0.6), same format for both "json" true and false.
Any ideas what may be wrong there? Same config as I posted above.

**Comment by bathos** [comment]
Although le_node is able to serialize actual Errors, Winston assumes transports can't, and prepares the data in advance. I'm not sure about this but I wonder if it involves the "meta" parameter, a Winston thing I don't fully understand the purpose of? This appears to be the logic Winston uses to prepare errors: https://github.com/winstonjs/winston/blob/master/lib/winston/exception.js

I also notice there’s an option for "humanReadableUnhandledException" -- before I probe deeper here, could you try seeing what that does?

**Comment by voitau** [comment]
I think now it is related to: https://github.com/logentries/le_node/issues/13

**Comment by bathos** [comment]
Agreed. We'll continue there, since the issue in this thread is seemingly dealt with now, while #13 describes this.
