### ISSUE TITLE
"printerrors" option doesn't seem to work as documented

### ISSUE THREAD

**Issue by uberbrady** [logentries/le_node#24]
```js
var logentries = require('node-logentries');

var log = logentries.logger({
  token: 'xxxx',
  printerror: true
});

console.warn("I AM ABOUT TO HAVE MY BIG ERROR _ HERE GOES!!!");

log.err("Hey look it's something. Or something.");
```

(This also happens if I leave out the "printerror" option, where it should default to true)

I *do* get the messages showing up in Logentries online - so it's doing its thing, but I would expect the "Hey look it's something" line to also be printed to STDERR or STDOUT or something.

I think I see the problem - I'll try to create a pull request for it.

**Comment by bathos** [comment]
The new client has a 'console' option. If the console option is true, logs of level 0-2 will use console.log, level 3 will use console.warn, and levels 4-7 will use console.error.
