### ISSUE TITLE
log.end() doesn't flush pending logs

### ISSUE THREAD

**Issue by msiebuhr** [logentries/le_node#27]
When using `log.end()` to do final cleanups in batch scripts (and cause the process to stop gracefully), it doesn't flush any remaining log entries.

I guess adding a `consume()`-call somewhere in `end()` would fix it, though I haven't tried it out.

**Comment by bathos** [comment]
In the new client at least, there's no need for such a method -- data is sent as soon as it can be sent unless you previously called '.cork()' (in which case, call '.uncork()'). It's a write stream so there's no flush in the read stream sense. To take care of final cleanups, write one last log and immediately listen for 'connection drain' -- when that has fired, you know all log data has written to the network connection.
