### ISSUE TITLE
Process exits before logging is initialized

### ISSUE THREAD

**Issue by coreybutler** [logentries/le_node#28]
If you follow the basic instructions on logentries.com (which still references v0.0.2) for using this, it will appear to fail because a connection is not established before logging methods are called. Ultimately, the process exits before the log entry is made. For example:

```js
var logentries = require('node-logentries');
var log = logentries.logger({
  token:'MY_TOKEN'
});
// level specific methods like 'info', 'debug', etc.
log.info("I'm a Lumberjack and I'm OK.")

// generic log method, also accepts JSON entries
log.log("debug", {sleep:"all night", work:"all day"})

console.log('All done.');
```
This script will exit without publishing a log entry.

It will succeed if you delay the exit, i.e. tack something like the following on the end of the script.

```js
setTimeout(function(){},500);
```

It would be nice if the `connect()` method were exposed so we could listen for the `connect` event before sending logs. 

The issue isn't apparent in long running process like a web server. It is apparent in worker scripts though, which launch-->run-->exit.

**Comment by bathos** [comment]
This is not applicable to the new client. The client will keep the event loop rolling until the write buffer has cleared.
