### ISSUE TITLE
Proxy server support?

### ISSUE THREAD

**Issue by pablote** [logentries/le_node#35]
Is there any support for using a proxy server for boxes that don't have direct internet access?

**Comment by chrismatheson** [comment]
Would this not be taken care of by the browser itself?

**Comment by vilda** [comment]
If it is server side behind proxy, it will needs to deal with proxies. In theory some HTTP header per every connection should suffice.

**Comment by bathos** [comment]
I'm not sure this is a question about le_node. Nothing prevents it from working with a proxy server as far as I can tell, but nothing really facilitates it either -- this is just a client library for an api endpoint.

Hmm... you can configure the target host and port, so you could send your logentries-ready log stream somewhere local for forwarding to the real service.
