### ISSUE TITLE
Cyclic

### ISSUE THREAD

**Issue by mbernath** [logentries/le_node#40]
**Problem:** 
When logging an object, le_node will JSON.stringify it. If the object contains circular references, this will lead to an Exception.
Of course, logged objects should normally not contain circular references, but it may always happen from time to time, and a logger shouldn't fail.

**Proposed solution:**
node-bunyan does a good job at preventing this error. Here's the stringifier code copied from node-bunyan. It should be fairly easy to implement.

```
   
try {
            str = JSON.stringify(rec, safeCycles()) + '\n';
        } catch (e) {
            if (safeJsonStringify) {
                str = safeJsonStringify(rec) + '\n';
            } else {
                var dedupKey = e.stack.split(/\n/g, 2).join('\n');
                _warn('bunyan: ERROR: Exception in '
                    + '`JSON.stringify(rec)`. You can install the '
                    + '"safe-json-stringify" module to have Bunyan fallback '
                    + 'to safer stringification. Record:\n'
                    + _indent(format('%s\n%s', util.inspect(rec), e.stack)),
                    dedupKey);
                str = format('(Exception in JSON.stringify(rec): %j. '
                    + 'See stderr for details.)\n', e.message);
            }
        }
```

and

```
// A JSON stringifier that handles cycles safely.
// Usage: JSON.stringify(obj, safeCycles())
function safeCycles() {
    var seen = [];
    return function (key, val) {
        if (!val || typeof (val) !== 'object') {
            return val;
        }
        if (seen.indexOf(val) !== -1) {
            return '[Circular]';
        }
        seen.push(val);
        return val;
    };
}
```

Any thoughts?

**Comment by ptdixon** [comment]
Trying to reproduce this exception. In my previous tests, circular / recursive object logging has been handled correctly..!?

**Comment by ptdixon** [comment]
That should be fixed now Marc.

Thanks for the heads up (I thought I had it covered, but my tests were bad)
Have replaced JSON.stringify() with util.inspect() which handles circular reference better.
Let me know if you still experience problems...

**Comment by oshbec** [comment]
It seems there is still [an instance](https://github.com/logentries/le_node/blob/8f6f07c5bf18104565e945db04afdf1bfc9e8a21/lib/le_node.js#L117) of `JSON.stringify()` when Winston is being used, causing errors when the object has a circular structure.

If `util.inspect()` isn't sufficient here for whatever reason, [substack/js-traverse](https://github.com/substack/js-traverse)
gives a pretty straightforward way to [scrub circular references](https://github.com/substack/js-traverse#scrub-circular-references), although @mbernath's proposed solution wouldn't require adding a dependency.
