### ISSUE TITLE
Option to handle uncaught exceptions with Winston?

### ISSUE THREAD

**Issue by akashgupta88** [logentries/le_node#45]
According to the [handling exceptions](https://github.com/winstonjs/winston#handling-uncaught-exceptions-with-winston) section for Winston, while adding a new transport, one can set the option to handle uncaught exceptions as: 

      winston.add(winston.transports.File, {
        filename: 'path/to/all-logs.log',
        handleExceptions: true
      });

How do I set the same while passing the winston instance to the logentries logger?

**Comment by bathos** [comment]
This works in the new client (also, I am fairly certain it worked in the old one -- this is functionality inherited from Winston’s Transport constructor.)

**Comment by akashgupta88** [comment]
@bathos Could you provide an example snippet of code for the same?
