### ISSUE TITLE
wish: document failure modes

### ISSUE THREAD

**Issue by markstos** [logentries/le_node#47]
I'm interested to see updated docs which cover the following:

What happens if the LogEntries API endpoint can't be reached for some reason? Does the code block? Are the incoming logs buffered until LogEntries becomes available? If the logs are buffered during an outage, are the accumulated on disk or in memory? Is there a limit to the buffer size? Could logs ever be lost during a LogEntries outage?

What happens if LogEntries is eabled for a trial but the trial ends, or the license otherwise expires? Does it crash the Node.js process if it's fails to initialize? Are the logs lost?

There is a handler for "error" events. Are there any particular known errors that may be emitted by the logging system?

**Comment by markstos** [comment]
From my reading of the [the code](https://github.com/logentries/le_node/blob/master/lib/le_node.js), it appears that if LogEntries were down, lines to log to it would be queued *in memory* with no limit. Given enough time or log volume, memory would become exhausted and the process possibly killled by an OOM Killer. The logs would be lost if LogEntries was the sole destination of the logs. 

That may be acceptable given the likely-low probability of the site being down, but is worth documenting. 

Besides the API being down, the design may be open to abuse when the API is *up*. If a bad actor could generate log events faster than they could be processed by LogEntries, the memory could be filled up, resulting in denial of service. 

That consider could be addressed by putting a maximum size on the queue. When the queue grows beyond a certain length, the oldest rows could be discarded to avoid unbounded memory growth.  The maximum queue size could likely be something rather high that is unlikely to be hit under normal conditions, like 10,000 or even 100,000 lines, depending on much memory typical logs would consume at those volumes.

**Comment by vilda** [comment]
The queue must be limited in size. If it is not it's a bug. Unfortunately the original author is not reachable anymore, but we have an alternative implementation prepared (https://github.com/bathos/logentries-client) which will eventually replace this one and be maintained.

**Comment by markstos** [comment]
Thanks for the response @vilda  I check out the new alternative implementation. It looks like perhaps better coding, docs and tests, but has the same problem. I opened a bug about it the new bug queue:

https://github.com/bathos/logentries-client/issues/4

**Comment by vilda** [comment]
Thanks Mark, I'll communicate this internally. Ideally if we can move the alternative implementation into this repo.

**Comment by bathos** [comment]
The new client is a writable stream implementation with sane buffer limits.
