### ISSUE TITLE
on log emitter fires before log is written

### ISSUE THREAD

**Issue by err0** [logentries/le_node#48]
My node function is not long lived. (AWS Lambda).  My last log call is not making it to logentries before the process exits.  I tried using the logger.on method but it appears the emitter is called before any log is written.

```javascript
// final log
log.log("info", { bucket: BucketID, session: sessionID, message: "All done!" });
// wait for the log to complete to call context.done
log.on('log', context.done(h_err, "Lambda processing complete."));
```

It would make more sense for the log event to emit _after_ the write is confirmed.

**Comment by StephenHynes7** [comment]
Hey there,

I would suggest trying out the following version of the Logentries client developer by one of our developers https://github.com/bathos/logentries-client

Regards,
Stephen

**Comment by bathos** [comment]
Afraid that wouldn't help in this case, Stephen. I had retained the behavior that the 'log' event fires after the log data is prepared and before it gets written (internally this is actually a bit different, but the issue described here would remain). I'll investigate possible solutions as I continue on the le_node=>logentries-client transition, but I suspect what will really be needed here is to expose a means for users to listen for the write buffer of the net/tls connection becoming empty (i.e. a new event). The underlying net connection is totally agnostic to the idea of "logs" -- it's just a stream of data, and I don't think there's any way to categorically say "one specific log entry has been written & transmitted".

**Comment by err0** [comment]
Thanks for the fast response guys.

I'd settle for "queue is empty" and "all packets acknowledged".  

In the grand scheme of things I realize this feels a bit edge case.  However with the rising popularity of micro services it's going to be more common.

**Comment by bathos** [comment]
The new version solves this by exposing the "connection drain" event.

**Comment by err0** [comment]
excellent.  I will give 1.0.2 a spin.  Thanks!
