### ISSUE TITLE
Build and publish 1.0.2 to npmjs.com

### ISSUE THREAD

**Issue by err0** [logentries/le_node#50]
https://www.npmjs.com/package/le_node has 0.2.1 as the latest version.

**Comment by bathos** [comment]
Yup. And I'm kind of wondering how to fix that, given that it seems to have been published by someone who no longer works here :/ ...?

Tonight I'll push these latest changes to the logentries-client repo so they can be accessed there at least.

**Comment by err0** [comment]
He may not be but his email address on npm is paul.dixon@logentries.com. turn on the mailbox, do a password reset and then add yourself as a collaborator and then remove him.

Normal channels is here: https://docs.npmjs.com/misc/disputes but it could take a couple weeks.

**Comment by bathos** [comment]
Yup, I think your first idea is the best. I can't do that myself so it won't happen until I can get word the correct people (meaning Monday at the earliest) so the logentries-client update (when I get home later) will be the solution for at least two days. That repo will remain active as an alias for the same code (when everything is right here, I'll just make it an import=>export of le_node).
