### ISSUE TITLE
Crasher:  Cannot read property 'minLevel' of undefined

### ISSUE THREAD

**Issue by markstos** [logentries/le_node#57]
This is with the current 1.0.4 version. The full stack trace looks something like this:

```
TypeError: Cannot read property 'minLevel' of undefined
    at LogentriesTransport._createDecoratedClass.get [as level] (../node_modules/le_node/lib/node_modules/logger.js:704:27)
```

I believe my sin was using `withLevels:true` as an option, but not also specifying a minLevel. If in fact I've done something wrong in my configuration, I would expect a friendly diagnostic. Otherwise, I presume this is a bug.

**Comment by bathos** [comment]
Bug indeed. I should really add a slew of new tests actually, especially for Winston, which is shrouded in a little mystery to me currently. Really I need to read the source for Winston’s `Transport` constructor, which `LogentriesTransport` extends -- this is probably not the only property that behaves badly in there.

**Comment by bathos** [comment]
(Just to clarify, minLevel and withLevels aren't dependent on each other, so the sin is entirely mine -- if I'm correct this is a bug specific to the winston transport form, but for all I know at this point it could be an issue with withLevels in general, which is a recent addition and I don't think I added tests for it yet. However, the default value for withLevels is already `true`, so until I get a chance to sort this out, you should be able to get the desired setting simply by omitting it.)

**Comment by markstos** [comment]
Thanks for the prompt response. 

If it helps, I was trying to define an array of transports like this:

```javascript
transports : [
        new (winston.transports.Console)(),
        new (winston.transports.Logentries)({
          secure : true,
          token: "xxx",
        })
]
```

Then later:

```javascript
logger.info("my log")
```

**Comment by markstos** [comment]
Ah. I tried to make a reduced-test-case that triggered the issue and I couldn't. So I took a look again at the full stack trace I had generated last night. Now that I'm less tired, I notice that the trigger starts with `node-config`, which is trying to clone some details because we have the transports listed in our our config file. It's during the cloning process that the issue is triggered:

```
TypeError: Cannot read property 'minLevel' of undefined
      at LogentriesTransport._createDecoratedClass.get [as level] (./node_modules/le_node/lib/node_modules/logger.js:704:27)
      at _clone (./node_modules/config/lib/config.js:1068:33)
      at _clone (./node_modules/config/lib/config.js:1068:20)
      at _clone (./node_modules/config/lib/config.js:1068:20)
      at cloneDeep (./node_modules/config/lib/config.js:1075:10)
      at ./node_modules/config/lib/config.js:1322:32
      at Array.forEach (native)
      at util.extendDeep (./node_modules/config/lib/config.js:1307:9)
      at new Config (./node_modules/config/lib/config.js:119:8)
      at Object.<anonymous> (./node_modules/config/lib/config.js:1593:31)
```

I may re-think that design. I only really meant to have *data* in my config file, not active objects. Changing my configuration a bit would avoid the issue with the objects not being clone-able by node-config.

**Comment by bathos** [comment]
Yup, looking at the code for that library’s [cloneDeep](https://github.com/lorenwest/node-config/blob/6a0453af30831c16c750c05be1c60364898e4023/lib/config.js#L1047) does explain it. It's unable to create an exact copy of the constructor. Both the constructor and its prototype have unenumerable methods and properties and private-symbol methods and properties. But I wouldn't say that this failure to clone is a bug on their part either; an ES6-style constructor is "unclonable" more or less by design.

**Comment by markstos** [comment]
Thanks for looking.
