### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by markstos** [logentries/le_node#59]
I trued just to run the simplest usage case, and it fails. I put this in "t.js" in the top of the project, and ran it:

```javascript
var Logger = require('./');
 var logger = new Logger({ token: "xxx" });  // but with a believed-valid token
  logger.on('error', function (errMsg) {
    console.log("Got an error %s",errMsg);
  });
  
logger.warning('test: The kittens have become alarmingly adorable.')
```

In my console, this is printed:

```
Got an error TypeError: Object #<Object> has no method 'awrap'
```

Nothing appears in the log at LogEntries.

**Comment by bathos** [comment]
Can you post the stack? I’m not sure what awrap is. It doesn’t (seem) to be in le_node and it doesn’t (seem) to be in Babel or CoreJS.

There are a few tests that are more or less variations on what you've got here and they're passing, and I’m logging with it myself without problems, so I’m not sure what angle to approach this from. Does it also occur with other log methods? Is it strings only or objects too?

**Comment by markstos** [comment]
In this case, there is no stack. When I grep the tree for "awap", I don't get any hits, either.

At this point, I'm on deadline to get this logging working today, so I'm going to switch for now to try logging to STDOUT, pipe that to `logger` which sends to `rsyslog` and then configure `rsyslog` to talk to LogEntries. We'll see how that works.   

I'll let you know if you get further with this, but you are welcome to close with "can't reproduce" it it does seem to be related to my particular environment.

**Comment by vespertilian** [comment]
I also cannot get a Hello World example to work. 

Returns an error:

TypeError: Cannot read property 'write' of undefined


Code
```
var logger = require('le_node');
// var winston = require('winston');
// var assert = require('assert');
module.exports = function(app, done) {
  console.log('00_setuplogging.js');
  var logger = new logger({token: 'xxx', console: true});

  logger.on('error', function(err){
    console.log('logentries logger error ' + err)
  })
  logger.on('log', function(){
    console.log('logentries logger logging')
  })

  logger.warning('the kittens have become alarmingly adorable.')
  logger.warning('testing 123.');

  done();
```

**Comment by bathos** [comment]
Thanks, vespertilian. At first I thought maybe this was a Winston version incompatibility issue, but then I realized your example isn't using Winston. I've tested the code above (excluding the wrapping function & `done()`) just now and it executed without errors. Since I can't debug it if I can't reproduce it, I'm going to need more data -- a stack trace, more code context, or the names of other npm modules are in use are all potentially useful info.

**Comment by bathos** [comment]
A follow up -- in your example, you use the same identifier for the constructor (outer scope) and the instance (function scope). Variable declaration in the function scope is hoisted; you no longer have access to the value of `logger` from the outer scope, not even for use in initializing the inner-scope variable. Thus the exported function in the above code, used without modification, will always produce a TypeError with the message "undefined is not a function.". But the error you supplied ("Cannot read property 'write' of undefined") suggests that nothing goes wrong until `warning` is called, meaning the code sample you gave is likely not identical to what you ran. Would you be able to provide a verbatim snippet of the code that produced the "write" related error, even if it has some unrelated stuff? That stuff might matter.

**Comment by vespertilian** [comment]
Hey Bathos, 

Thank you for your quick response.

Not sure why but when I copied the code from vim Logger had a lower case "l". I included the verbatim snippet. Below the verbatim copy, I linked you to a git repository with a sample app which should be more useful.

```
var Logger = require('le_node');
// var winston = require('winston');
// var assert = require('assert');
module.exports = function(app, done) {
  console.log('00_setupLogging.js');
  var logger = new Logger({token: 'xxx', console: true});

  logger.on('error', function(err){
    console.log('Logentries logger error ' + err)
  })
  logger.on('log', function(){
    console.log('Logentries logger logging')
  })

  logger.warning('The kittens have become alarmingly adorable.')
  logger.warning('Testing 123.');

  done();

  // assert(winston.transports.Logentries);
  //
  // var isTestEnv = (process.env.NODE_ENV || 'development') === 'test';
  //
  // var logger = new (winston.Logger)({
  //   transports: [
  //     new (winston.transports.Console)({ colorize: true, timestamp: true }),
  //   ]
  // });
  //
  // if(process.env.NODE_ENV === 'production'){
  //   logger.add(winston.transports.Logentries, { token: 'b13798d9-cf4c-4dfa-8728-88a8c1715d87' });
  //   logger.info('Just setup logentries for production');
  //   done()
  // }
  // else if(process.env.NODE_ENV === 'staging'){
  //   logger.add(winston.transports.Logentries, { token: '64389089-d4ee-4e57-9e17-65bb4ae5df70' });
  //   logger.info('Just setup logentries for staging');
  //   done()
  // }
  // else if(!isTestEnv){
  //   //Must be dev
  //   logger.add(winston.transports.Logentries, { token: 'de55fdcb-a941-4ff0-a1a9-0306de08fd5f' });
  //   logger.info('Just setup logentries for development');
  //   logger.log('Just setup logentries for development');
  //   logger.debug('Just setup logentries for development');
  //   done()
  // }

}
```

I am using loopback by Strongloop I created a sample application here:
https://github.com/vespertilian/strongloop_loopback_with_logentries 

I just removed my token, from the boot script located at:

server/boot/00_setupLogging.js

Read about boot-scripts here http://docs.strongloop.com/display/public/LB/Defining+boot+scripts 

Using Node v0.12.2

After you NPM install and change the the token to your own token you should be able to start the server with:

slc run.

Here is the error. 
```
INFO strong-agent v1.5.1 profiling app 'logentries' pid '13787'
INFO strong-agent[13787] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
Setup logging
00_setupLogging.js
warning The kittens have become alarmingly adorable.
Logentries logger logging
warning Testing 123.
Logentries logger logging
Logentries logger error TypeError: Cannot read property 'write' of undefined
Logentries logger error TypeError: Cannot read property 'write' of undefined
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/

```

**Comment by bathos** [comment]
Great, thanks for the context -- tentatively, I think that gives us an explanation. I haven't yet confirmed it but I'll tell you my immediate impression:

This appears to be a very similar case to what Markstos had encountered when using the node-config library. Like node-config, the strongloop bootstrapping script tries to perform a deep clone on the objects in the configuration so that it can alter them without mutating the originals. While it was always possible for "deep cloning" constructors to go awry in JS, with ES6 stuff it's pretty much guaranteed to fail, and the Logger constructor has symbolic members that cannot be cloned using the techniques in lodash's deep clone method (which is what strongloop appears to use).

If that is the explanation, I'm afraid the current version of le_node will not be compatible with configuration system that do stuff like that. The last version of le_node prior to 1.0 will very likely to play nice lodash's deep clone function, however. There is no real way to reliably clone arbitrary constructors if you don't know what's in them anymore; that's what the prototype chain is for (actually, even Object.create would work I think!).

I'll investigate this further though since I'm not 100% sure that's what's going on yet.

**Comment by bathos** [comment]
Update: Although strongloop clones some config stuff, in this case that isn't taking place. Having the repo to experiment with is very helpful.

**Comment by vespertilian** [comment]
@bathos Thanks for all your hard work.

**Comment by bathos** [comment]
@vespertilian Great news, I can fix this: it hinges on installing 5.5.0+ of the babel-runtime dependency. Simply locking the runtime version in at its original 5.4.7 will solve it. But what really causes it? That's still a mystery to me:

There were a lot of changes in the runtime between 5.4.7 and 5.5.0, making it tough to definitively identify the cause. We know it's nothing from the transpiling phase; the built files are identical. However, the "awrap" bit from markstos' original issue, and the fact that the errors seem to be associated with async/await methods is a good clue. I found `awrap` in regenerator -- and Babel bumped their regenerator version in 5.5.0. It would seem that something broke the runtime's handling of async/await (at least in our case -- the context of class bodies maybe?) between versions 0.8.20 and 0.8.28:

https://github.com/facebook/regenerator/compare/v0.8.20...v0.8.28

Still a lot to look at. My gut draws me towards this commit though:

https://github.com/facebook/regenerator/commit/a4d2143bc8a8c639e90471942c63df89c7a22064

But that's all I've got, a gut feeling -- regenerator is a whole world unto itself and I'm not sure I could describe this problem adequately enough to open an issue there; for all I know, the apparance of it being regenerator-related could still be a red herring.

I'll commit/publish a patch later today with the runtime version locked. Until then, you can test for yourself whether this solves it for you, too (`npm install babel-runtime@5.4.7`).

**Comment by markstos** [comment]
Nice investigative work!

**Comment by vespertilian** [comment]
@bathos Thanks for your timely help. 

I have some other work I can continue with so I will just wait for your update. Do you think I could get my Log-entries trial reset? 

That account is under cameron@gofar.co

**Comment by bathos** [comment]
I'm still running into problems. Although it seems babel-runtime / regenerator is involved, further testing showed that using 5.4.7 didn't always fix it. There's something else different about the environments and it's baffling that it works in my working directory and Jenkins but not on a fresh local install. So I still don't have a fix, though obviously there *is one* @_@

As far as your account goes, I'm afraid I don't have control over that myself. However I'll talk to someone from support about it tomorrow.

**Comment by markstos** [comment]
Based on what's known so far, it appears that porting the code back from ES6 to ES5 would be a possible fix.

For now, I'm just going to log to STDOUT, pipe that to `logger` and let `rsyslog` communicate with LogEntries.

**Comment by bathos** [comment]
We’re good to go. I ultimately needed to use [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to lock down versions of dependencies of dependencies, because the gobble transformer had its own duplicates that used the incompatible versions.

**Comment by markstos** [comment]
Good find!  I ended up using shrinkwrap as well. Now I just need to keep straight `npm-shrinkwrap` vs `npm shrinkwrap`.

**Comment by vespertilian** [comment]
@bathos Finally got back to setting up the logging. Sent my first log today tanks for fixing this.
