### ISSUE TITLE
proxy-settings?

### ISSUE THREAD

**Issue by alre1011** [logentries/le_node#60]
Does the le_node  module support proxy settings? I couldn't find information about that and I'm afraid it doesn't. I'm stuck in a company's network and need it.

**Comment by bathos** [comment]
Hi alre1011. Can you explain more what you mean by "support proxy settings"?

**Comment by alre1011** [comment]
Hey bathos. I have a small nodeJS-application and I want it to log to logentries. But the application runs on a system that is in my company's network, hence the requests to logentries (made by the le_node-module) need to use proxy settings. That's why I am looking for a way to "tell" le_node to use my company's proxy.

**Comment by bathos** [comment]
One solution would be to configure 'host' and 'port' to point to whatever you need them to be, then make the appropriate corresponding proxy configuration to tell it where such traffic ought to be routed.

If you don't have the ability to configure the proxy itself, though, there are ways to configure proxy settings at the node level:

http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

These concerns aren't normally addressed at the "node module" level -- not really the right scope -- so I'm closing the issue, though hopefully that link will get you started.
