### ISSUE TITLE
SSL encrypted connection configuration does not work

### ISSUE THREAD

**Issue by voitau** [logentries/le_node#64]
I tried some combinations based on the configuration options available in this client to use SSL encrypted connection. Unfortunately, nothing worked. Here are results of investigation:

Here is what they say for configuration of SSL encrypted connection in official [documentation](https://logentries.com/doc/input-token/):
> For untrusted networks you can open an SSL encrypted connection to api.logentries.com, port number 20000.

However, default secure port is [443](https://github.com/logentries/le_node/blob/master/src/node_modules/defaults.js#L10), what makes it impossible just to use `secure` option without specifying port. Same for host, where the value here is [data.logentries.com](https://github.com/logentries/le_node/blob/master/src/node_modules/defaults.js#L4), but has to be `api.logentries.com`.

So I tried some options.
Does not send anything to LE:
```
secure: true,
host: 'api.logentries.com',
port: '20000'
```
Fails and crashes application:
```
host: 'api.logentries.com',
port: '20000'
```

Also, observed some issues with configuration of ports in general. Ignores the port:
```
host: 'data.logentries.com:12345'
```

Fails to start:
```
host: 'data.logentries.com',
port: '12345'
```

**Comment by bathos** [comment]
I won’t be able to investigate this until the weekend, but I can say that the use of 443 with data.logentries.com is intentional. This [change](https://github.com/bathos/logentries-client/commit/cbe814a0b4c6aa0d73b422cf2410702898639f4e) came from @StephenHynes7  and I believe it’s what we’re moving towards, though I don’t know the details of why.

But it clearly should also work with the api / 20000 endpoint, and the host option is supposed to allow shorthand for setting port, too, so regardless of the above, both of those look like bugs.

**Comment by voitau** [comment]
Hi, any news on this?

**Comment by bathos** [comment]
Yup -- well, as of just now, since you reminded me, thanks :)

It looks like both problems are the consequence of really simple mistakes:

    opts.port || opts.secure ? defaults.portSecure : defaults.port;

should be:

    opts.port || (opts.secure ? defaults.portSecure : defaults.port);

And:

    this[$host] = url.hostName || defaults.host;

should be:

    this[$host] = url.hostname || defaults.host;

I’m not 100% sure that explains what you encountered, but I'm going to push these fixes up now since they’re at least clearly part of the story.

**Comment by bathos** [comment]
1.0.10 is live now with those fixes

**Comment by voitau** [comment]
I tried with a new version, SSL connection to api.logentries.com:20000 still does not work.

**Comment by StephenHynes7** [comment]
@voitau is there any particular reason why you want to send to api.logentries.com instead of data? data.logentries.com would be the perfered endpoint for Token TCP connections.

**Comment by bathos** [comment]
@voitau -- specifically what happens? Does it still throw? Does the host/port not get set correctly? Does it appear to work in node, but nothing shows up in the logentries app?

**Comment by voitau** [comment]
@StephenHynes7, api.* is mentioned in the official documentation as the proper endpoint for SSL (https://logentries.com/doc/input-token/):
> For untrusted networks you can open an SSL encrypted connection to api.logentries.com, port number 20000.

@bathos, it does not show up in logentries app.
Configuration is:
```javascript
winston.add(winston.transports.Logentries, {
  token: 'SOME_TOKEN,
  secure: true,
  host: 'api.logentries.com',
  port: '20000'
});
```

I tried with and without secure, api.* and data.*. Does not work unless everything removed besides token, which will make it work without SSL.

**Comment by voitau** [comment]
Hello everyone, any news here? Thanks!

**Comment by bathos** [comment]
I'll give this another go, voitau.  The old endpoint is still active and accepts the same format as the new one, so it must be an le_node-specific issue. Maybe I'm overriding the custom port when secure == true, will check it out now.

**Comment by bathos** [comment]
Not sure why this was so mysterious. Port was only accepting numbers, not strings. I'll have it parseInt first.

**Comment by bathos** [comment]
Fixed in 1.0.14

**Comment by voitau** [comment]
Maybe I'm doing something wrong, but I'm trying to test this and the message is not displayed in logentries admin UI. What is the configuration you are using to test this? What is the secure flag value, how do you define host and port?

**Comment by bathos** [comment]
I used the configuration above and everything was being set correctly (it was dropping port, if it was a string, previously). However I didn’t get to test it against a real account, so it remains possible that there’s another issue, though it seems pretty unlikely since it was sending to the right port & host in the mock. You definitely got 1.0.14?

**Comment by voitau** [comment]
Yes, it is 1.0.14 and this is my test code:
```javascript
var Logger = require('le_node');
var winston = require('winston');

winston.add(winston.transports.Logentries, {
  token: 'SOME_TOKEN',
  secure: true,
  host: 'api.logentries.com',
  port: '20000'
});

winston.log('info', { key: 'value' });
```

**Comment by voitau** [comment]
Should this one be reopened? Thanks.

**Comment by bathos** [comment]
Yeah, I'll investigate again, though at this point I'm pretty confused since in tests the host & port were correct for me. I'll try it against a real account.

**Comment by voitau** [comment]
Hello, any updates here? Thanks.

**Comment by StephenHynes7** [comment]
Does using data.lognetries.com and port 443 work at all? I wouldn't advise using api.logentries.com as an endpoint versus data.logentries.com since it is not optimised for Token based forwarding.

**Comment by voitau** [comment]
@StephenHynes7 I tried all possible combinations I mentioned above and none of them worked for me. However, the official documentation says https://logentries.com/doc/input-token/:
"For untrusted networks you can open an SSL encrypted connection to api.logentries.com, port number 20000."

**Comment by StephenHynes7** [comment]
@voitau that part is likely out of date, i will look to change it. Really it should be data.logentries.com and not api.

**Comment by voitau** [comment]
Confirming that it works with `secure: true` and no other additional settings. Ticket can be closed, thanks!

**Comment by voitau** [comment]
Okay, found the root cause. It did not work with node v0.10, but works with v0.12.
