### ISSUE TITLE
Setting a hook on console object with LogEntries

### ISSUE THREAD

**Issue by bendpx** [logentries/le_node#68]
Hey, 
I'm trying to set a hook on the Console object to use the log entries logger so we won't need to require the module everywhere in the app

the code looks like that:
var util = require('util'),
    Logger = require('le_node'),
    config = require('config');

function formatArgs(args) {
    return [util.format.apply(util.format, Array.prototype.slice.call(args))];
}

var logger = new Logger({token: config.logEntriesToken});

// Set a HOOK over the console.logging function so we can use console.log/debug/warn/error around without importing the logger module
console.log = function () {
    logger.info.apply(logger, formatArgs(arguments));
};
console.info = function () {
    logger.info.apply(logger, formatArgs(arguments));
};
console.warn = function () {
    logger.warn.apply(logger, formatArgs(arguments));
};
console.error = function () {
    logger.error.apply(logger, formatArgs(arguments));
};
console.debug = function () {
    logger.debug.apply(logger, formatArgs(arguments));
};

logger.stream = {
    write: function (message, encoding) {
        console.log(message);
    }
};

logger.on('error', function(e) {
    console.log('test');
});
logger.once('connection drain', function(e) {
    console.log('test');
    
});

the logs stops while the server is bootstrapping (many logs are sent at that point)
![screen shot 2015-07-20 at 7 50 06 pm](https://cloud.githubusercontent.com/assets/11241713/8781558/6e676938-2f18-11e5-9910-d3e23d6350a1.png)

What am I doing wrong?

**Comment by bendpx** [comment]
A proposal for a better way to make logentries logger global in the app is also fine

**Comment by bathos** [comment]
Well ... you're overwriting methods on a global object, and your error handler on Logger calls a method on that global object that's actually an alias for a method on Logger now. So it is very easy to create endless recursion in the event of any error, and this is to some extent a good object lesson about not modifying native objects. :)

That said, there’s really nothing bad about the premise. I’ve done it before, too. Console *technically* isn’t a language-level object, so this isn’t *technically* a sin... right?

As for what’s going on in that code -- well, there are layers and details here that strike me as ‘off’ but perhaps I lack context. There are two things I’d point out right away, though:

 1. You’re adding what seems to be a ‘fake’ stream interface. What is that for? Logger is a real Writable. You can call write, you can pipe to it, etc.
 2. Many of the "applies" there are ... questionable :) -- for one, consider that util.format always returns a single string, regardless of the number of arguments it receives. You only need one apply in one spot to achieve what you want. So the extra complexity might be hiding problems.

Here's my (untested) impression of what you might be looking for:

```js
var config = require('config');
var Logger = require('le_node');
var util = require('util');

var logger = new Logger({ token: config.logEntriesToken, console: false });

logger.on('error', function(err) { ...  });
logger.on('connection drain', function() { ... });

var slice = Array.prototype.slice;

function formatArgsAnd(fn) {
  return function() {
    var args = slice.call(arguments);
    var str = util.format.apply(null, args);
    fn(str);
  };
}

function wrapConsole(m) {
  var log = logger[m.logger].bind(logger);
  console[m.console] = formatArgsAnd(log);
}

var methods = [
  { console: 'log',   logger: 'info' },
  { console: 'info',  logger: 'info' },
  { console: 'warn',  logger: 'warning' },
  { console: 'error', logger: 'err' },
  { console: 'debug', logger: 'debug' }
];

methods.forEach(wrapConsole);
```

**Comment by bendpx** [comment]
Thanks dude, code worked. I understand the issue

**Comment by bathos** [comment]
Awesome. What’s that IDE btw? Looks interesting.

**Comment by bendpx** [comment]
It's WebStorm 8 with dracula theme, love it
