### ISSUE TITLE
setting minLevel doesn't work with winston

### ISSUE THREAD

**Issue by annanhan** [logentries/le_node#71]
If the minLevel property is set with Winston, nothing gets logged. It looks like the LogentriesTransport translates the transport level to a number that tries to correspond with a Winston level, however, the Winston mapping goes from 'log level string' to 'number'. This causes the lookup to fail and nothing is logged. 

Here is my setup:
![code](https://cloud.githubusercontent.com/assets/10620173/9228425/71dfd872-40e6-11e5-97f5-c16643c4ba36.png)

Here is what happens in the debugger:
![debugger](https://cloud.githubusercontent.com/assets/10620173/9228751/dc4ae37c-40e7-11e5-8014-896187b1e5e4.png)

See how the transport.level is 3. The lookup for self.levels[transport.level] isn't going to work. The mapping is string -> number. Setting minLevel to a number has the same effect.

**Comment by bathos** [comment]
Thanks for the clear explanation. Fix is now live.

**Comment by annanhan** [comment]
Thanks for the quick fix!
