### ISSUE TITLE
Difficult to set an error handler for bunyan streams

### ISSUE THREAD

**Issue by egergo** [logentries/le_node#73]
Logger error events must be handled, otherwise an uncaught exception is thrown. When a bunyan stream is created with bunyanStream(), the Logger object is hidden behind a Symbol

```javascript
this[$Logger] = new Logger(opts)
```

This way the user has to use reflection to subscribe to errors.

**Comment by bathos** [comment]
True, I noticed this issue recently myself. To keep the interface clean, what I think makes the most sense is to bubble all events up to the bunyan stream object, which is an event emitter itself anyway -- this make sense to you?

**Comment by egergo** [comment]
Yes, absolutely.
