### ISSUE TITLE
'TypeError: Cannot convert object to primitive value' thrown when trying to serialise object values with null prototypes

### ISSUE THREAD

**Issue by irond13** [logentries/le_node#74]
Some libraries that we use create objects using Object.create(null) (possibly for performance reasons). The objects therefore have no valueOf or toString functions and thus cause the serialiser to bomb at https://github.com/logentries/le_node/blob/master/src/node_modules/serialize.js#L48 with the above TypeError.

**Comment by bathos** [comment]
Thanks, can’t say I anticipated that. I’ll add some guards for this case.

**Comment by irond13** [comment]
Cool, thanks! I just realised I can put my own guards in a custom replacer. I used the following:

if (_.isObject(val) && ! (val.toString || val.valueOf)) return JSON.parse(JSON.stringify(val)); //May not be that performant
