### ISSUE TITLE
Memory leak with Bunyan

### ISSUE THREAD

**Issue by vespertilian** [logentries/le_node#79]
I think I have found a memory leak when using le_node with Bunyan.

I am using Express and Loopback, which is where I originally saw the issue.

This repository is paired back to just le_node and bunyan: https://github.com/vespertilian/lenode_bunyan_memory_leak

If you perform a heap-dump using Logentries with Bunyan you end up with a growing heap size. 
If you then run the same test using Bunyan, logging to standard out instead the heap size does not grow. 

@bathos I had a quick look at your code, but I am not sure what would be causing it.

**Comment by fastfedora** [comment]
Did you ever figure out what was causing this?

I'm experience a memory leak with le_node + bunyan. I haven't been able to track down where it's occurring, but if I comment out `le_node.bunyanStream()` when configuring Bunyan in my codebase, the memory leak disappears.
