### ISSUE TITLE
This plugin doesn't with winston version 2.

### ISSUE THREAD

**Issue by Sh33pman** [logentries/le_node#87]
I do know that it the dependencies of the module indicate that it works with winston version 1.0.0 and up. It still causes issues if you already have winston version 2 installed before you install le_node.

Would be useful if the documentation has a warning for this scenario. 

The levels for the log names doesn't seems to work together correctly.

**Comment by bathos** [comment]
Looks like Winston 2 just came out and, being a major version, has a lot of breaking changes. Would you be able to get specific about what exactly no longer works with le_node in Winston 2?

**Comment by Sh33pman** [comment]
Correct they reversed the level mapping but now what happens is if you leave the LogEntries transport on minLevel = 0. It will only log errors because winston will then only allow errors. 

If you change this to anything above 0 it will never log anything to LogEntries.

From debugging it seems this line of code is the issue:
https://github.com/winstonjs/winston/blob/2.1.1/lib/winston/logger.js#L153
```javascript
return (transport.level && self.levels[transport.level] >= self.levels[level])
      || (!transport.level && self.levels[self.level] >= self.levels[level]);
```

Values when logging an info message is:
```
transport.level = info 
self.levels[transport.level] = 0 
self.levels[level] = 2
```

This causes it to return false and the message is not logged.

**Comment by bathos** [comment]
Thanks, that makes sense. The tricky bit is that we'll need to figure out the Winston version and tailor behavior accordingly, since this is the opposite of how Winston 1 and Bunyan work.

**Comment by bathos** [comment]
Or perhaps we could disable the level check when Winston is in use altogether. I think this would be safe since Winston must not forward events that don't meet its level-level anyway, and the internal LE client in the transport isn't exposed so people wouldn't be relying on it to manage this anyway.

**Comment by mrbichel** [comment]
Do you have an idea for a temporary fix for this? Or is it easier to revert to an earlier version of winston for now?

**Comment by Sh33pman** [comment]
Going back to version 1.1.2 of winston was pretty easy. Did have to change
anything where the winston code was used.

**Comment by jhenthorn** [comment]
+1 on this

**Comment by PuKoren** [comment]
+1

**Comment by nathanmarks** [comment]
@mrbichel Here's my temp fix, I reversed the winston levels and passed them to the logentries constructor.

```js
    new Logentries({
      handleExceptions: true,
      json: true,
      level: 'debug',
      levels: { error: 5, warn: 4, info: 3, verbose: 2, debug: 1, silly: 0 },
      secure: true,
      token: process.env.LE_TOKEN
    })
```
