### ISSUE TITLE
Publish 1.1.2 to NPM

### ISSUE THREAD

**Issue by jarrodconnolly** [logentries/le_node#88]
Please publish the latest 1.1.2 to NPM to get the fix for the vulnerable dependency out there.

**Comment by jarrodconnolly** [comment]
@StephenHynes7 
Thank you for the fix to the vulnerable dependency, can we please get 1.1.2 pushed to npm?

**Comment by jljorgenson18** [comment]
+1. v1.1.1 is having installation issues as well and is exiting with a status code 1. This is causing builds to break.

**Comment by cdibened** [comment]
Any idea when this will be published?  Security checks are failing on an app I'm building.  Is there anything that can be done to move this along faster?

**Comment by bathos** [comment]
1.2 is up
