### ISSUE TITLE
npm shrinkwrap results in extraneous package errors

### ISSUE THREAD

**Issue by TSteele27** [logentries/le_node#90]
when running npm shrinkwrap on my project that depends on le_node I get an extraneous package error and it fails to generate a valid npm-shrinkwrap.json. Here is the output of the shrinkwrap command:

 npm ERR! extraneous: mitm@1.1.0 D:\services\project\node_modules\le_node\node_modules\mitm
npm ERR! extraneous: winston@1.0.0 D:\services\project\node_modules\le_node\node_modules\winston
npm ERR! extraneous: bunyan@1.3.5 D:\services\project\node_modules\le_node\node_modules\bunyan
npm ERR! extraneous: tap-spec@3.0.0 D:\services\project\node_modules\le_node\node_modules\tap-spec
npm ERR! extraneous: tape@4.0.0 D:\services\project\node_modules\le_node\node_modules\tape
npm ERR! extraneous: gobble@0.10.2 D:\services\project\node_modules\le_node\node_modules\gobble
npm ERR! extraneous: gobble-babel@5.1.0 D:\services\project\node_modules\le_node\node_modules\gobble-babel
npm ERR! extraneous: gobble-cli@0.4.2 D:\services\project\node_modules\le_node\node_modules\gobble-cli

it looks like there are extra packages in the npm-shrinkwrap.json that are not included in the package.json as dependencies.

**Comment by mcgauranc** [comment]
Hi there, does running npm prune resolve the issue for you?
The inclusion of devDependencies in the npm-shrinkwrap would seem to be the culprit here.

**Comment by TSteele27** [comment]
running npm prune does fix the issue and allows me to successfully shrinkwrap the application.

**Comment by bathos** [comment]
I'm going to see if I can sort out the shrinkwrap issue later this week. I'd like to get it out of there now.

**Comment by TSteele27** [comment]
Any movement on this issue? I am now getting errors when even when I prune and shrink wrap:
````
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have codependency@0.1.3 (expected: 0.1.4) D:\services\catalog\node_modules\le_node\node_modules\codependency
npm ERR! extraneous: codependency@0.1.3 D:\services\catalog\node_modules\le_node\node_modules\codependency
````

I'm using node v5.5.0 and npm v3.3.12

**Comment by AndrewKeig** [comment]
+1

**Comment by TSteele27** [comment]
@bathos Have you been able to look into this issue. We are trying to update our applications to use the latest version of le_node since the version we are on uses some packages with known vulnerabilities, but this is blocking us from updating. Thanks.

**Comment by StephenHynes7** [comment]
Should be fixed now with the latest release.
