### ISSUE TITLE
No entries in log

### ISSUE THREAD

**Issue by dnfrolov** [logentries/le_node#98]
node -v v4.2.2
le_node -v 1.2.0

```
const Logger = require('le_node')
const logger = new Logger({
      token: process.env.LOGENTRIES_TOKEN
    })
logger.err(new Error)
```

it works good if I just switch to **node-logentries**

**Comment by StephenHynes7** [comment]
Tested this on my machine and everything looks to be working correctly
![node](https://cloud.githubusercontent.com/assets/4609179/12815699/dc6970de-cb3f-11e5-81a6-e8f9fee6a72c.png)

Can you double check your logentries account to see if the data has come in,

**Comment by dnfrolov** [comment]
double check - works. might have an issue with connection. thanks
